### ISSUE TITLE
请教如何屏蔽露点图片？

### ISSUE THREAD

**Issue by Xialichong** [chenjiandongx/yummy-girls#6]
RT

研究了一天了（偷笑），如何避免抓取那些走光的图片？

**Comment by chenjiandongx** [comment]
还有露点图片的 我怎么不知道 在哪里 😄

**Comment by Xialichong** [comment]
咳咳… 是我上错车啦

陈键冬 <notifications@github.com> 于2019年3月14日周四 上午8:58写道：

**Comment by chenjiandongx** [comment]
露点也挺好的 没事
